### ISSUE TITLE
Translations cannot be added in Symfony 3+

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/sanitycheck-bundle#2]
**Describe the bug**
AddTranslationsPass adds translations from the sanitycheck lib to the Symfony container. In Symfony 3 the translator constructor has changed which breaks this compiler pass.

**Affected version(s)**
6.2.x

**Expected behavior**
The compiler pass should work for all Symfony versions.

**Comment by UlrichKu** [comment]
Is the milestone correct here?

**Comment by umulmrum** [comment]
Yes :-)
